server:
  hostname: localhost
  port: 8080

spring:
  application:
    name: movie
  datasource:
    url: jdbc:postgresql://db:5432/movie_db
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
  flyway:
    enabled: true
    locations: classpath:db/migration
    schemas: public
    baselineOnMigrate: true
    validateOnMigrate: true
    cleanOnValidationError: false

jwt:
  secret: hits2025hits2025hits2025hits2025hits2025hits2025hits2025hits
  access-lifetime: 15m
  refresh-lifetime: 7d

# знаю, что нельзя указывать секретную информацию в конфиг файле, но мне просто было лень настраивать переменные окружения :D